# Generated by Django 5.0.3 on 2026-02-04 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absent',
            options={'ordering': ['-create_time']},
        ),
    ]
